#include <iostream>
#include <windows.h>
#include "Menu.h"
using namespace std;

void MostrarBienvenida(){
	HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
	

    
	
	SetConsoleTextAttribute(hConsole, 12);
	system("cls");
	cout<<"BBBBBBBBBBBBBBBBB   IIIIIIIIIIEEEEEEEEEEEEEEEEEEEEEENNNNNNNN        NNNNNNNNVVVVVVVV           VVVVVVVVEEEEEEEEEEEEEEEEEEEEEENNNNNNNN        NNNNNNNNIIIIIIIIIIDDDDDDDDDDDDD             OOOOOOOOO        SSSSSSSSSSSSSSS                                          \n";                 
    cout<<"B::::::::::::::::B  I::::::::IE::::::::::::::::::::EN:::::::N       N::::::NV::::::V           V::::::VE::::::::::::::::::::EN:::::::N       N::::::NI::::::::ID::::::::::::DDD        OO:::::::::OO    SS:::::::::::::::S                                        \n";                  
    cout<<"B::::::BBBBBB:::::B I::::::::IE::::::::::::::::::::EN::::::::N      N::::::NV::::::V           V::::::VE::::::::::::::::::::EN::::::::N      N::::::NI::::::::ID:::::::::::::::DD    OO:::::::::::::OO S:::::SSSSSS::::::S                                     \n";                  
    cout<<"BB:::::B     B:::::BII::::::IIEE::::::EEEEEEEEE::::EN:::::::::N     N::::::NV::::::V           V::::::VEE::::::EEEEEEEEE::::EN:::::::::N     N::::::NII::::::IIDDD:::::DDDDD:::::D  O:::::::OOO:::::::OS:::::S     SSSSSSS                                    \n";                  
    cout<<"B::::B     B:::::B  I::::I     E:::::E       EEEEEE N::::::::::N    N::::::N V:::::V           V:::::V  E:::::E       EEEEEE N::::::::::N    N::::::N  I::::I    D:::::D    D:::::D O::::::O   O::::::OS:::::S                                             \n";                  
    cout<<"B::::B     B:::::B  I::::I     E:::::E              N:::::::::::N   N::::::N  V:::::V         V:::::V   E:::::E              N:::::::::::N   N::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::OS:::::S                                             \n";                  
    cout<<"B::::BBBBBB:::::B   I::::I     E::::::EEEEEEEEEE    N:::::::N::::N  N::::::N   V:::::V       V:::::V    E::::::EEEEEEEEEE    N:::::::N::::N  N::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::O S::::SSSS                                      \n";                 
    cout<<"B:::::::::::::BB    I::::I     E:::::::::::::::E    N::::::N N::::N N::::::N    V:::::V     V:::::V     E:::::::::::::::E    N::::::N N::::N N::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::O  SS::::::SSSSS                              \n";                 
    cout<<"B::::BBBBBB:::::B   I::::I     E:::::::::::::::E    N::::::N  N::::N:::::::N     V:::::V   V:::::V      E:::::::::::::::E    N::::::N  N::::N:::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::O    SSS::::::::SS                           \n";                  
    cout<<"B::::B     B:::::B  I::::I     E::::::EEEEEEEEEE    N::::::N   N:::::::::::N      V:::::V V:::::V       E::::::EEEEEEEEEE    N::::::N   N:::::::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::O       SSSSSS::::S                         \n";                  
    cout<<"B::::B     B:::::B  I::::I     E:::::E              N::::::N    N::::::::::N       V:::::V:::::V        E:::::E              N::::::N    N::::::::::N  I::::I    D:::::D     D:::::DO:::::O     O:::::O            S:::::S                      \n";                 
    cout<<"B::::B     B:::::B  I::::I     E:::::E       EEEEEE N::::::N     N:::::::::N        V:::::::::V         E:::::E       EEEEEE N::::::N     N:::::::::N  I::::I    D:::::D    D:::::D O::::::O   O::::::O             S:::::S                  \n";                  
    cout<<"BB:::::BBBBBB::::::BII::::::IIEE::::::EEEEEEEE:::::EN::::::N      N::::::::N         V:::::::V         EE::::::EEEEEEEE:::::EN::::::N      N::::::::N II::::::IIDDD:::::DDDDD:::::D  O:::::::OOO:::::::O SSSSSSS     S:::::S                 \n";                  
    cout<<"B:::::::::::::::::B I::::::::IE::::::::::::::::::::EN::::::N       N:::::::N          V:::::V          E::::::::::::::::::::EN::::::N       N:::::::NI::::::::ID:::::::::::::::DD     OO:::::::::::::OO S::::::SSSSSS:::::S               \n";                 
    cout<<"B::::::::::::::::B  I::::::::IE::::::::::::::::::::EN::::::N        N::::::N           V:::V           E::::::::::::::::::::EN::::::N        N::::::NI::::::::ID::::::::::::DDD         OO:::::::::OO   S:::::::::::::::SS              \n";                  
    cout<<"BBBBBBBBBBBBBBBBB   IIIIIIIIIIEEEEEEEEEEEEEEEEEEEEEENNNNNNNN         NNNNNNN            VVV            EEEEEEEEEEEEEEEEEEEEEENNNNNNNN         NNNNNNNIIIIIIIIIIDDDDDDDDDDDDD              OOOOOOOOO      SSSSSSSSSSSSSSS             \n";                                                                                                                                                                                                                                                                                      
    cout<<endl; 
	cout<<"                                                                                                           AAA                      \n";                 
    cout<<"                                                                                                          A:::A                     \n";                  
    cout<<"                                                                                                         A:::::A                    \n";                  
    cout<<"                                                                                                        A:::::::A                   \n";                  
    cout<<"                                                                                                       A:::::::::A                  \n";                  
    cout<<"                                                                                                      A:::::A:::::A                 \n";                  
    cout<<"                                                                                                     A:::::A A:::::A                 \n";                 
    cout<<"                                                                                                    A:::::A   A:::::A                \n";                 
    cout<<"                                                                                                   A:::::A     A:::::A              \n";                  
    cout<<"                                                                                                  A:::::AAAAAAAAA:::::A             \n";                  
    cout<<"                                                                                                 A:::::::::::::::::::::A             \n";                 
    cout<<"                                                                                                A:::::AAAAAAAAAAAAA:::::A           \n";                  
    cout<<"                                                                                               A:::::A             A:::::A          \n";                  
    cout<<"                                                                                              A:::::A               A:::::A          \n";                 
    cout<<"                                                                                             A:::::A                 A:::::A        \n";                  
    cout<<"                                                                                            AAAAAAA                   AAAAAAA       \n";   
	cout<<endl;                                                                                                                                                                                                                                                                                    
    cout<<"                                                             HHHHHHHHH     HHHHHHHHH     OOOOOOOOO     TTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEELLLLLLLLLLL                                                                                                                   \n";   
    cout<<"                                                             H:::::::H     H:::::::H   OO:::::::::OO   T:::::::::::::::::::::TE::::::::::::::::::::EL:::::::::L                                                                                                                   \n";   
    cout<<"                                                             H:::::::H     H:::::::H OO:::::::::::::OO T:::::::::::::::::::::TE::::::::::::::::::::EL:::::::::L                                                                                                                    \n";  
    cout<<"                                                             HH::::::H     H::::::HHO:::::::OOO:::::::OT:::::TT:::::::TT:::::TEE::::::EEEEEEEEE::::ELL:::::::LL                                                                                                                   \n";   
    cout<<"                                                               H:::::H     H:::::H  O::::::O   O::::::OTTTTTT  T:::::T  TTTTTT  E:::::E       EEEEEE  L:::::L                                                                                                                    \n";    
    cout<<"                                                               H:::::H     H:::::H  O:::::O     O:::::O        T:::::T          E:::::E               L:::::L                                                                                                                    \n";    
    cout<<"                                                               H::::::HHHHH::::::H  O:::::O     O:::::O        T:::::T          E::::::EEEEEEEEEE     L:::::L                                                                                                                    \n";    
    cout<<"                                                               H:::::::::::::::::H  O:::::O     O:::::O        T:::::T          E:::::::::::::::E     L:::::L                                                                                                                    \n";    
    cout<<"                                                               H:::::::::::::::::H  O:::::O     O:::::O        T:::::T          E:::::::::::::::E     L:::::L                                                                                                                    \n";    
    cout<<"                                                               H::::::HHHHH::::::H  O:::::O     O:::::O        T:::::T          E::::::EEEEEEEEEE     L:::::L                                                                                                                    \n";    
    cout<<"                                                               H:::::H     H:::::H  O:::::O     O:::::O        T:::::T          E:::::E               L:::::L                                                                                                                    \n";    
    cout<<"                                                               H:::::H     H:::::H  O::::::O   O::::::O        T:::::T          E:::::E       EEEEEE  L:::::L         LLLLLL                                                                                                     \n";    
    cout<<"                                                             HH::::::H     H::::::HHO:::::::OOO:::::::O      TT:::::::TT      EE::::::EEEEEEEE:::::ELL:::::::LLLLLLLLL:::::L                                                                                                     \n";    
    cout<<"                                                             H:::::::H     H:::::::H OO:::::::::::::OO       T:::::::::T      E::::::::::::::::::::EL::::::::::::::::::::::L                                                                                                     \n";    
    cout<<"                                                             H:::::::H     H:::::::H   OO:::::::::OO         T:::::::::T      E::::::::::::::::::::EL::::::::::::::::::::::L                                                                                                     \n";    
    cout<<"                                                             HHHHHHHHH     HHHHHHHHH     OOOOOOOOO           TTTTTTTTTTT      EEEEEEEEEEEEEEEEEEEEEELLLLLLLLLLLLLLLLLLLLLLLL                                                                                                     \n";    
    cout<<endl;                                                                                                                                                                                                                                                                                                 
    cout<<"                                       CCCCCCCCCCCCCUUUUUUUU     UUUUUUUU           AAA               NNNNNNNN        NNNNNNNNTTTTTTTTTTTTTTTTTTTTTTTIIIIIIIIII      CCCCCCCCCCCCC     OOOOOOOOO                                                                                 \n";    
    cout<<"                                    CCC::::::::::::CU::::::U     U::::::U          A:::A              N:::::::N       N::::::NT:::::::::::::::::::::TI::::::::I   CCC::::::::::::C   OO:::::::::OO                                                                               \n";    
    cout<<"                                  CC:::::::::::::::CU::::::U     U::::::U         A:::::A             N::::::::N      N::::::NT:::::::::::::::::::::TI::::::::I CC:::::::::::::::C OO:::::::::::::OO                                                                             \n";    
    cout<<"                                 C:::::CCCCCCCC::::CUU:::::U     U:::::UU        A:::::::A            N:::::::::N     N::::::NT:::::TT:::::::TT:::::TII::::::IIC:::::CCCCCCCC::::CO:::::::OOO:::::::O                                                                            \n";    
    cout<<"                                C:::::C       CCCCCC U:::::U     U:::::U        A:::::::::A           N::::::::::N    N::::::NTTTTTT  T:::::T  TTTTTT  I::::I C:::::C       CCCCCCO::::::O   O::::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U       A:::::A:::::A          N:::::::::::N   N::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U      A:::::A A:::::A         N:::::::N::::N  N::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U     A:::::A   A:::::A        N::::::N N::::N N::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U    A:::::A     A:::::A       N::::::N  N::::N:::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U   A:::::AAAAAAAAA:::::A      N::::::N   N:::::::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                            \n";    
    cout<<"                               C:::::C               U:::::D     D:::::U  A:::::::::::::::::::::A     N::::::N    N::::::::::N        T:::::T          I::::IC:::::C              O:::::O     O:::::O                                                                             \n";   
    cout<<"                                C:::::C       CCCCCC U::::::U   U::::::U A:::::AAAAAAAAAAAAA:::::A    N::::::N     N:::::::::N        T:::::T          I::::I C:::::C       CCCCCCO::::::O   O::::::O                                                                             \n";   
    cout<<"                                 C:::::CCCCCCCC::::C U:::::::UUU:::::::UA:::::A             A:::::A   N::::::N      N::::::::N      TT:::::::TT      II::::::IIC:::::CCCCCCCC::::CO:::::::OOO:::::::O                                                                            \n";    
    cout<<"                                  CC:::::::::::::::C  UU:::::::::::::UUA:::::A               A:::::A  N::::::N       N:::::::N      T:::::::::T      I::::::::I CC:::::::::::::::C OO:::::::::::::OO                                                                            \n";     
    cout<<"                                    CCC::::::::::::C    UU:::::::::UU A:::::A                 A:::::A N::::::N        N::::::N      T:::::::::T      I::::::::I   CCC::::::::::::C   OO:::::::::OO                                                                              \n";     
    cout<<"                                       CCCCCCCCCCCCC      UUUUUUUUU  AAAAAAA                   AAAAAAANNNNNNNN         NNNNNNN      TTTTTTTTTTT      IIIIIIIIII      CCCCCCCCCCCCC     OOOOOOOOO                                      \n";
	        
    cout<<"\nPresione una tecla para continuar...";
    system("pause>nul");                                                                                                          

}

